#' @title Learn how to set up priors for a Mahalanobis distance point process model with climate covariance matrix caculated from the poisson likelihood
#' @description
#' Identify the correct structure to specify the priors for a euclidean distance model
#' @param mu.b.mean Numeric, with as many elements as covariates in the ppmve model. Must be specified in the same order they appear in "covariate.names".
#' Each value indicates the likely niche centroid coordinates.
#' @param mu.b.prec Numeric, with as many elements as covariates in the ppmve model. Must be specified in the same order they appear in "covariate.names".
#' Each value indicates the precision (1/variance) of the niche centroid coordinates.
#' @param R A square matrix array, with rows and columns equal to the length of covariate names, and must be positive definite. 
#' may be generated by inverting a covariance matrix.
#' @param beta.mean A single numeric positive or negative value, inticates the mean of the global intercept.
#' @param beta.prec A single numeric positive, inticates the precision of the global intercept.
#' @examples
#' priors <- mahalLocallocalPriors(mu.b.mean = rep(0, 4),
#'                                 mu.b.prec = rep(1.0E-4, 4),
#'                                 R = diag(4),
#'                                 beta.mean = 0,
#'                                 beta.prec = 1.0E-4)
#' @export

mahalLocallocalPriors <- function(mu.b.mean = NULL,
                                  mu.b.prec = NULL,
                                  R = NULL,
                                  beta.mean = NULL,
                                  beta.prec = NULL){
  
  if(dim(R)[1] != dim(R)[2] | length(mu.b.mean) != length(mu.b.prec)){
    stop("Please make sure that cent.mean, cent.prec, mu.b.mean and mu.b.prec contain the same  number of elements.\n
     The number of rows and columns of R must alsoo be equal to the number of elements of the previous priors")
  }

  if(any(mu.b.prec < 0)){
    stop("Please make sure that all values of mu.b.prec are positive")
  }

  if(beta.prec < 0){
    stop("Please make sure that all values of tau.min, tau.mx and beta.prec are positive")
  }

  if(length(beta.mean) > 1 | length(beta.prec) > 1){
    stop("Please provide a sigle value for beta.mean and beta.prec")
  }
  
  priors <- list(mu.b.mean = mu.b.mean,
                 mu.b.prec = mu.b.prec,
                 R = R,
                 beta.mean = beta.mean,
                 beta.prec = beta.prec)

  return(priors)
}